version: '3'
services:
  api:
    image: makinhs/rest-api-tutorial
    build: .
    networks:
      - backend
    ports:
      - "3600:3600"
    depends_on:
      - cassandra

  cassandra:
    image: cassandra
    volumes:
      - ./data:/data/db
    networks:
      - backend
    ports:
      - "7000:7000"

  web-cli:
    image: makinhs/rest-api-tutorial
    links:
      - cassandra
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
